title: SideStore Docs
description: SideStore is the home of untethered sideloading. We are committed to bringing a safe and simple sideloading experience to our users. All contributions are welcome!
theme: just-the-docs

url: https://wiki.sidestore.io

aux_links:
  Home: https://sidestore.io
  GitHub: https://github.com/sidestore
  Patreon: https://www.patreon.com/sidestore
  Discord: https://discord.gg/RgpFBX3Q3k
  Twitter: https://twitter.com/sidestore_io

favicon_ico: "/assets/icons/favicon.ico"

aux_links_new_tab: true

callouts:
  warning:
    title: Warning
    color: red
