/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Installation',
      items: ['installation/prerequisites', 'installation/install'],
    },
    'faq',
    {
      type: 'category',
      label: 'Troubleshooting',
      items: ['troubleshooting/error-codes', 'troubleshooting/troubleshooting', 'troubleshooting/common-issues'],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/alternative', 'advanced/anisette', 'advanced/app-sources', 'advanced/jit', 'advanced/pairing-file', 'advanced/url-schema'],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: ['contributing/contributing', 'contributing/formatting', 'contributing/advanced-formatting'],
    },
    'release-notes',
  ],
};

export default sidebars;
