/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    'faq',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/prerequisites', 'getting-started/pairing-file', 'getting-started/windows', 'getting-started/mac', 'getting-started/linux', 'getting-started/post-install'],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: ['troubleshooting/error-codes', 'troubleshooting/troubleshooting'],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/anisette', 'advanced/app-sources', 'advanced/url-schema'],
    },
  ],
};

export default sidebars;
